const navMenuValues = [
	{
		PrazoInicio: "",
		PrazoTermino: "",
		ProjetoTitulo: "",
		ProjetoTituloEN: "",
		ProjetoArea: "",
		ResponsavelNome: "",
		ResponsavelInstituicao: "",
		ResponsavelDepartamento: "",
		ResponsavelLattes: "",
		ResponsavelExperienciaSN: "",
		ResponsavelExperiencia: "",
		ResponsavelTempoExperiencia: "",
		ResponsavelTreinamentoSN: "",
		ResponsavelTreinamento: "",
		ResponsavelTempoTreinamento: "",
		ResponsavelVinculo: "",
		ResponsavelTelefone: "",
		ResponsavelEmail: "",
		ResponsavelLocal: "",
		ResponsavelLocalexperimentos: "",
		Resumo: "",
		Objetivos: "",
		Justificativa: "",
		Relevancia: "",
		ModeloAnimalEspecie: "asdf",
		ModeloAnimalProcedenciaBioterioSN: "sim",
		ModeloAnimalProcedenciaBioterioNome: "asdf",
		ModeloAnimalProcedenciaBioterioLocalizacao: "asdf",
		ModeloAnimalSilvestreSN: "sim",
		ModeloAnimalSilvestreAnimal: "asdf",
		ModeloAnimalSilvestreNumSolicitacao: "asdf",
		ModeloAnimalSilvestreOutra: "asdf",
		ModeloAnimalSilvestreQual: "asdf",
		ModeloAnimalModificadoSN: "sim",
		ModeloAnimalModificadoNumCQB: "asdf",
		ModeloAnimalInvasividade: "gi1",
		ModeloAnimalUsoMaterialSN: "sim",
		ModeloAnimalUsoMaterial: "asdf",
		ModeloAnimalUsoMaterialProtocolo: "asdf",
		ModeloAnimalCondicoesLocal: "asdf",
		ModeloAnimalCondicoes: "asdf",
		ModeloAnimalAlojamento: "gaiola",
		ModeloAnimalAnimaisPorGaiola: 1234,
		ModeloAnimalAnimaisCama: "asdf",
		ModeloAnimalCondicoesAlimentacao: "asdf",
		ModeloAnimalCondicoesFonteAgua: "asdf",
		ModeloAnimalCondicoesLotacao: "asdf",
		ModeloAnimalCondicoesExaustaoSN: "sim",
		animais: [],
		animaisTotais: 0,
		farmacos: [],
		anexos: [],
	}
]

export default navMenuValues
